DefaultTerms:
  - InternalCode: '814e894a-6f79-45f1-aaaa-90ef30e7c062'
    Name: 'BG_Entity_Identity'
    NamingConvention: '{{ModelObject.Name}}_ID'
  - InternalCode: 'b5610dd2-4c6d-414d-ac01-8a3affa55b07'
    Name: 'BG_Entity_ForeignKey_Identity'
    NamingConvention: '{{ReferencedModelObject.Name}}_{{Role}}_ID'
  - InternalCode: '59d597b6-3b78-42c9-85f0-02c68f428094'
    Name: 'BG_Fact_ForeignKey_Identity'
    NamingConvention: '{{ReferencedModelObject.Name}}_{{Role}}_ID'
  - InternalCode: '618f7171-3c96-4093-9f01-05b68d3ee3f1'
    Name: 'BG_MartFact_ForeignKey_Identity'
    NamingConvention: '{{ReferencedModelObject.Name}}_{{Role}}_ID'
